version: "3.8"

services:
  app1:
    build: .
    networks:
      - appnet

  app2:
    build: .
    networks:
      - appnet

  app3:
    build: .
    networks:
      - appnet

  app4:
    build: .
    networks:
      - appnet

  app5:
    build: .
    networks:
      - appnet

  app6:
    build: .
    networks:
      - appnet

  nginx:
    image: nginx:alpine
    ports:
      - "5067:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2
      - app3
      - app4
      - app5
      - app6
    networks:
      - appnet

networks:
  appnet:
