version: "3.8"

services:
  app:
    build: .
    expose:
      - "5666"
    networks:
      - appnet
    deploy:
      replicas: 6

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - appnet

networks:
  appnet: