version: "3.8"

services:
  app1:
    build: .
    expose:
      - "5666"
    networks:
      - appnet

  app2:
    build: .
    expose:
      - "5666"
    networks:
      - appnet

  app3:
    build: .
    expose:
      - "5666"
    networks:
      - appnet

  app4:
    build: .
    expose:
      - "5666"
    networks:
      - appnet

  app5:
    build: .
    expose:
      - "5666"
    networks:
      - appnet

  app6:
    build: .
    expose:
      - "5666"
    networks:
      - appnet

  nginx:
    image: nginx:alpine
    ports:
      - "5067:80"
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
        content: |
          events {}

          http {
              upstream app_cluster {
                  server app1:5666;
                  server app2:5666;
                  server app3:5666;
                  server app4:5666;
                  server app5:5666;
                  server app6:5666;
              }

              server {
                  listen 80;

                  location / {
                      proxy_pass http://app_cluster;
                      proxy_set_header Host $host;
                      proxy_set_header X-Real-IP $remote_addr;
                      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                      proxy_set_header X-Forwarded-Proto $scheme;
                  }
              }
          }
    depends_on:
      - app1
      - app2
      - app3
      - app4
      - app5
      - app6
    networks:
      - appnet

networks:
  appnet: